services:

  nginx:
    image: nginx:stable
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    restart: always
    volumes:
      - ./src:/var/www/html

  mariadb:
    image: mariadb:stable
    restart: always
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
