services:

  nginx:
    image: nginx:1.29-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: unless-stopped

  php:
    build: .
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: mariadb:11.8
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  dbdata:
